[package]
name = "minimal_failing_example"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
debian-packaging = { version = "0.18.0", default-features = false }
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
